### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by unix2dos** [thuanowa/tmux-fzf-session-switch#12]
<img width="1058" alt="image" src="https://github.com/thuanowa/tmux-fzf-session-switch/assets/22365670/bf8005a0-ffed-4784-aebd-78b59e69f4f7">

Why does this plugin show install session ？

**Comment by cutbypham** [comment]
i just test, i think it worked
![image](https://github.com/thuanowa/tmux-fzf-session-switch/assets/40050527/94d3bf60-e91a-4ecf-bf29-1a9cb668bf75)

```
set -g @plugin 'thuanowa/tmux-fzf-session-switch'
```
![image](https://github.com/thuanowa/tmux-fzf-session-switch/assets/40050527/b54eee38-2610-4862-be93-faf53f2e7705)

![image](https://github.com/thuanowa/tmux-fzf-session-switch/assets/40050527/96926dfc-f61d-4361-9d5b-520b0e6f1c19)

**Comment by thuanowa** [comment]
![Uploading image.png…]()

**Comment by cutbypham** [comment]
@unix2dos i think, mission `''` in your tmux config

![image](https://github.com/thuanowa/tmux-fzf-session-switch/assets/40050527/2e9281f0-2a69-4c38-90bc-bd90c7a19341)

**Comment by unix2dos** [comment]
A problem caused by another plugin。
