### ISSUE TITLE
Allow configuration of keybinding

### ISSUE THREAD

**Issue by erikw** [thuanowa/tmux-fzf-session-switch#3]
I know it's already mention in the README , and let's put it here as well as someone might miss it in the README.

It would be great to be able to configure the default keybinding from the default one. A popular choice would be to override the default session selector at `<prefix>-s`.

Looking how other tmux plugins configure keybindings, I would expect it to look like this in `tmux.conf`

```conf
# Change keybinding to <prefix>-s
set -g @fzf-session-switch-bind 's'
```

Here's an example of how tmux-fzf-url implements configurable keybinding:
https://github.com/wfxr/tmux-fzf-url/blob/1241fc5682850fe41812cad81c76541674ee305b/fzf-url.tmux#L17

**Comment by erikw** [comment]
Hmm it looks like this is already supported via the option `@fzf-goto-session`

[tmux_option_goto="@fzf-goto-session"
](https://github.com/thuanpham2311/tmux-fzf-session-switch/blob/4654cd281715c2f1af5f1cf4ea9b16ec6b448aae/main.tmux#L6)

I have to try this when I'm back at my computer.

**Comment by cutbypham** [comment]
thanks :heart:
