### ISSUE TITLE
feat: option search panes + sessions +windows

### ISSUE THREAD

**Issue by cutbypham** [thuanowa/tmux-fzf-session-switch#8]

**Comment by praveenperera** [comment]
this would be great, or search for pane separately

**Comment by cutbypham** [comment]
show in popup:
- session name | window name | pane. fzf preview will show windows content
like this:
![image](https://user-images.githubusercontent.com/40050527/224458672-745fba3e-149f-4fb0-8d8a-df10b4966f82.png)

**Comment by erikw** [comment]
Hm while this is cool, it's quite a big change in the behavior of the plugin. I definitely preferred the old behavior. I need only to switch between the sessions. Could we make this configurable, so that it's opt-in? :)

**Comment by cutbypham** [comment]
> Hm while this is cool, it's quite a big change in the behavior of the plugin. I definitely preferred the old behavior. I need only to switch between the sessions. Could we make this configurable, so that it's opt-in? :)

![image](https://user-images.githubusercontent.com/40050527/227929127-2a287e67-0b8d-4296-9c2a-e8c47f5d4052.png)

yep, good to have option to disable.

**Comment by cutbypham** [comment]
> Hm while this is cool, it's quite a big change in the behavior of the plugin. I definitely preferred the old behavior. I need only to switch between the sessions. Could we make this configurable, so that it's opt-in? :)

option is here

```bash
set-option -g @fzf-goto-session-only 'true'
```

**Comment by erikw** [comment]
@thuanowa thanks, it works! 🎉
